export const RPG_CONFIG = {
  XP_BASE_NIVEL: 25, CURVA_EXPONENTE: 1.85, SEMANAS_ESTIMADAS_LV100: 12,
  PESO_CONSISTENCIA: 0.50, PESO_DISCIPLINA: 0.20, PESO_EVOLUCAO: 0.15, PESO_PERFORMANCE: 0.10, PESO_CALORIAS: 0.05,
  BASE_SEMANA_CONSISTENCIA: 1800, BASE_DISCIPLINA: 700,
  BONUS_STREAK_DISCIPLINA_PER: 60, BONUS_STREAK_DISCIPLINA_MAX: 2000, BONUS_SEMANA_PERFEITA: 500,
  MULTIPLICADOR_STREAK_BASE: 1.0, MULTIPLICADOR_STREAK_INCREMENTO: 0.015,
  MULTIPLICADOR_STREAK_TETO: 1.30, STREAK_MAXIMO_CALCULO: 20,
  ESCUDO_SEMANAS_NECESSARIAS: 3, ESCUDO_MAXIMO_ARMAZENADO: 2, ESCUDO_COOLDOWN_SEMANAS: 1,
  XP_EXERCICIO_BASE_EVOLUCAO: 30, MAX_EXERCICIOS_EVOLUCAO: 5, EVOLUCAO_MIN_PCT: 0.025, EVOLUCAO_FATOR_MAX: 2.0,
  XP_MAX_PERFORMANCE_POR_TREINO: 350,
  SERIES_LIMITE_FULL_XP: 15, SERIES_LIMITE_PARCIAL_XP: 20, SERIES_LIMITE_ZERO_XP: 25,
  REPS_LIMITE_POR_SERIE: 30, CARGA_MINIMA_PCT_30: 0.30, CARGA_MINIMA_PCT_50: 0.50,
  CARGA_MINIMA_XP_30: 0.10, CARGA_MINIMA_XP_50: 0.50,
  XP_MAX_CALORIAS_POR_TREINO: 100, CALORIAS_DIMINISHING_APOS: 1000, CALORIAS_DIMINISHING_FATOR: 0.5,
  XP_MAX_MUSCULAR_POR_TREINO: 300, MUSCULO_FATOR_REDUCAO_3X: 0.50,
  EQUILIBRIO_DIFERENCA_MAX_NIVEIS: 15, EQUILIBRIO_MULTIPLICADOR: 1.10,
  ASCENSAO_BONUS_XP_PERCENTUAL: 0.05, ASCENSAO_BONUS_XP_TETO: 0.50,
  RETORNO_STREAK_MINIMA_QUEBRADA: 4, RETORNO_SEMANAS_INATIVIDADE: 2, RETORNO_SEMANAS_PARA_BONUS: 2, RETORNO_XP_BONUS: 2000,
  XP_MAX_SEMANAL: 15000,
  XP_NIVEL_ATRIBUTO_BASE: 100, XP_NIVEL_ATRIBUTO_EXP: 1.6,
  PR_AUMENTO_MAX_VALIDO_PCT: 0.10,
  DIAS_ONBOARDING_DESTAQUE: 7, ESCUDO_ONBOARDING_SEMANA: 3,
};

export const RANKS = [
  "NOVATO I", "NOVATO II", "APRENDIZ I", "APRENDIZ II", "GUERREIRO I", "GUERREIRO II",
  "ELITE I", "ELITE II", "CAMPEÃO I", "CAMPEÃO II", "MESTRE I", "MESTRE II",
  "GRÃO-MESTRE I", "GRÃO-MESTRE II", "LENDÁRIO I", "LENDÁRIO II",
];

export const CARDIO_MET = {
  caminhada: { leve: 2.8, moderada: 3.8, forte: 5.5 },
  bicicleta: { leve: 4.0, moderada: 6.8, forte: 10.0 },
};

export const MET_MUSCULACAO = 5.0;

export const DEFAULT_BODY = { weight: 82, height: 178, age: 24, secPerSet: 150 };
