export const DEFAULT_EXERCISES = {
  supino_maquina: { name: "Supino máquina", muscle: "Peito" },
  supino_inclinado: { name: "Supino inclinado c/ halteres", muscle: "Peito" },
  peck_deck: { name: "Peck deck (crucifixo)", muscle: "Peito" },
  triceps_corda: { name: "Tríceps corda no pulley", muscle: "Tríceps" },
  triceps_coice: { name: "Tríceps coice / corda pronada", muscle: "Tríceps" },
  elevacao_lateral: { name: "Elevação lateral na polia", muscle: "Ombro" },
  face_pull: { name: "Face pull", muscle: "Ombro posterior" },
  leg_press: { name: "Leg press 45°", muscle: "Perna" },
  extensora: { name: "Cadeira extensora", muscle: "Quadríceps" },
  flexora: { name: "Mesa flexora", muscle: "Posterior de coxa" },
  romana: { name: "Cadeira romana", muscle: "Abdômen" },
  panturrilha: { name: "Panturrilha", muscle: "Panturrilha" },
  puxada: { name: "Puxada frente (pulldown)", muscle: "Costa" },
  remada_maquina: { name: "Remada máquina sentada", muscle: "Costa" },
  remada_unilateral: { name: "Remada unilateral c/ apoio", muscle: "Costa" },
  rosca_direta: { name: "Rosca direta", muscle: "Bíceps" },
  rosca_concentrada: { name: "Rosca concentrada", muscle: "Bíceps" },
};
